### ISSUE TITLE
Do you have a roadmap? 

### ISSUE THREAD

**Issue by leroy0211** [steverhoades/oauth2-openid-connect-server#19]
Do you have a roadmap for this implementation? 

For example: 

- implement the /.well-known/openid-configuration handler
- implement a token-introspection handler
- ...

**Comment by steverhoades** [comment]
The short answer is there is no roadmap for new features at the moment. This library does exactly what I need it to do. I've purposely kept it as simple as possible.  

If there are missing features you would like to see please let me know about them!

**Comment by leroy0211** [comment]
Aah, I see you only implemented the OIDC core RFC. If that is your only goal, then I'm all OK with that.

I wanted to have the OIDC Discovery and Dynamic Registration too in my setup.

**Comment by steverhoades** [comment]
@leroy0211 Sorry for taking awhile to respond to this. I'll take a more in-depth look at these. I do believe these features would be great additions to this library. Thanks!

**Comment by stadja** [comment]
Hello :)
I wanted to know if there were plans to add the /token/introspection and the /userinfo endpoint ?

Explaination:
https://connect2id.com/products/server/docs/api/token-introspection
https://connect2id.com/products/server/docs/api/userinfo

**Comment by ralfbecker** [comment]
I can second that it would be a good enhancement. 
I had to implement it on top of open-id-connect using one pull request from the underlaying League OAuth2 server, when I implemented (OpenID Connect for EGroupware)[https://github.com/EGroupware/openid].
I'm happy to prepare both a pull request, if I know it will be merged.

Ralf

**Comment by steverhoades** [comment]
@stadja @ralfbecker I would definitely be interested in any improvements to this library you would be willing to contribute. My time is very limited at the moment but as soon as I can i'll review the token-introspection and usreinfo links provided above.

**Comment by ralfbecker** [comment]
I added now a couple more enhancements to my [OpenID Connect server for EGroupware](https://github.com/EGroupware/openid):
- [x] fix League OAuth2 server to support multiple response_type(s), currently it neither [splits response_type by space](https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/ImplicitGrant.php#L109), nor does it send responses for more then one grant, [see response in this ticket](https://github.com/thephpleague/oauth2-server/issues/903#issuecomment-423891504)
- [x] support response_type "id_token" or "token id_token" containing just an id_token (JWT) or additional to access_token an id_token
- [x] support hyprid flow / response_type contains additional "code" to also return an auth_code
- [x] add additional [OpenID Connect standard scopes](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims): profile, address, phone

Ralf
